In [11]:
import pandas as pd 
df = pd.read_excel(r"C:\Users\ADMIN\OneDrive\Desktop\grade9.xlsx") 

df

    Position                  NAME  ENG  KISW  ...  C.A  SST  IRE  TOTAL
0          1         BWANA IDI ALI   59    66  ...   75   70   65    528
1          2     ABDIHAFID MOHAMUD   58    49  ...   70   50   59    495
2          3          BONAYA GWIYO   60    62  ...   54   56   56    484
3          4      ABDIQANI HUSSEIN   47    57  ...   50   56   60    430
4          5            YUSRA JUMA   58    61  ...   38   56   39    426
5          6           KOMORA SAID   39    56  ...   48   46   55    425
6          7         HAGERERA BUYA   57    66  ...   42   53   43    420
7          8          IDRISS JAMAA   43    53  ...   38   50   56    415
8          9  ABDIRAHMAN ABDI MIRE   46    43  ...   80   64   38    414
9         10           ABDALA SAID   46    57  ...   48   38   42    400
10        11           AHMED DUALE   43    43  ...   56   43   37    399
11        12          MALIKA HATIE   57    54  ...   48   58   43    396
12        13   ABDINASIR ABDULLAHI   54    37  ...   38   48   67    390
13        14             LEILA ALI   33    31  ...   54   63   51    370
14        15         ABDALLAH ROVA   38    54  ...   42   23   37    362
15        16     ASHWAQ ABDIRAHMAN   27    33  ...   56   68   43    353
16        17           OMAR GAWAWA   42    45  ...   50   46   26    351
17        18      ABDIRAHMAN SALAT   41    42  ...   28   53   52    345
18        19       HIRIBAE HUSSEIN   47    49  ...   24   46   32    344
19        20           FARDOSA ALI   44    41  ...   40   46   44    340
20        21       BUKO AWADH SAID   52    57  ...   32   24   41    321
21        22             OMAR MUSE   34    35  ...   30   48   41    314
22        23       ABDIWAHAB AHMED   32    31  ...   52   55   24    305
23        24          NIMA MOHAMED   30    40  ...   32   48   38    303
24        25       FARDOSA MOHAMED   33    33  ...   40   44   38    302
25        26         BUSHRA FATUMA   41    52  ...   32   46   30    290
26        27   ABDIHAKIM ABDULLAHI   36    43  ...   30   34   38    279
27        28        REHEMA ISMAIL    31    43  ...   42   38   23    277
28        29          HANAN BASHIR   31    27  ...   42   46   31    273
29        30     MWANAHADIE SWALEH   24    45  ...   34   40   20    271
30        31            AYAN GULED   35    28  ...   36   54   19    270
31        32          AHMED HASSAN   32    28  ...   42   34   21    264
32        33      YASMIN ABDI KUNO   26    35  ...   15   53   22    258
33        34         AWADHI HASSAN   27    47  ...   24   31   38    253
34        35           YASMIN ABDI   20    18  ...   18   51   24    247
35        36        KHALIDIN HAMDI   15    18  ...   22   49   26    230
36        37       ABDIMALIK HAMDI   25    23  ...   18   25   55    221
37        38              ASMA ALI   30    28  ...   32   41   20    216
38        39             SARWA ALI   23    20  ...   30   25   26    205
39        40           SADIK DAHIR   30    16  ...   24   46   23    203
40        41       ABDIRAHMAN ADEN   17    27  ...   20   38    6    196
41        42      BAHSAN ABDULLAHI   23    25  ...   30   16   19    172
42        43             ADAN ABDI   13    20  ...   22    6   24    162

[43 rows x 12 columns]

In [18]:
from my_functions import cbc_report_generator
report = cbc_report_generator(df) 

report['CLOSING_DATE'] = '28-03-2026'
report['OPENING_DATE'] = '31-04-2026'

report

    Position                  NAME  ... CLOSING_DATE OPENING_DATE
0          1         BWANA IDI ALI  ...   28-03-2026   31-04-2026
1          2     ABDIHAFID MOHAMUD  ...   28-03-2026   31-04-2026
2          3          BONAYA GWIYO  ...   28-03-2026   31-04-2026
3          4      ABDIQANI HUSSEIN  ...   28-03-2026   31-04-2026
4          5            YUSRA JUMA  ...   28-03-2026   31-04-2026
5          6           KOMORA SAID  ...   28-03-2026   31-04-2026
6          7         HAGERERA BUYA  ...   28-03-2026   31-04-2026
7          8          IDRISS JAMAA  ...   28-03-2026   31-04-2026
8          9  ABDIRAHMAN ABDI MIRE  ...   28-03-2026   31-04-2026
9         10           ABDALA SAID  ...   28-03-2026   31-04-2026
10        11           AHMED DUALE  ...   28-03-2026   31-04-2026
11        12          MALIKA HATIE  ...   28-03-2026   31-04-2026
12        13   ABDINASIR ABDULLAHI  ...   28-03-2026   31-04-2026
13        14             LEILA ALI  ...   28-03-2026   31-04-2026
14        15         ABDALLAH ROVA  ...   28-03-2026   31-04-2026
15        16     ASHWAQ ABDIRAHMAN  ...   28-03-2026   31-04-2026
16        17           OMAR GAWAWA  ...   28-03-2026   31-04-2026
17        18      ABDIRAHMAN SALAT  ...   28-03-2026   31-04-2026
18        19       HIRIBAE HUSSEIN  ...   28-03-2026   31-04-2026
19        20           FARDOSA ALI  ...   28-03-2026   31-04-2026
20        21       BUKO AWADH SAID  ...   28-03-2026   31-04-2026
21        22             OMAR MUSE  ...   28-03-2026   31-04-2026
22        23       ABDIWAHAB AHMED  ...   28-03-2026   31-04-2026
23        24          NIMA MOHAMED  ...   28-03-2026   31-04-2026
24        25       FARDOSA MOHAMED  ...   28-03-2026   31-04-2026
25        26         BUSHRA FATUMA  ...   28-03-2026   31-04-2026
26        27   ABDIHAKIM ABDULLAHI  ...   28-03-2026   31-04-2026
27        28        REHEMA ISMAIL   ...   28-03-2026   31-04-2026
28        29          HANAN BASHIR  ...   28-03-2026   31-04-2026
29        30     MWANAHADIE SWALEH  ...   28-03-2026   31-04-2026
30        31            AYAN GULED  ...   28-03-2026   31-04-2026
31        32          AHMED HASSAN  ...   28-03-2026   31-04-2026
32        33      YASMIN ABDI KUNO  ...   28-03-2026   31-04-2026
33        34         AWADHI HASSAN  ...   28-03-2026   31-04-2026
34        35           YASMIN ABDI  ...   28-03-2026   31-04-2026
35        36        KHALIDIN HAMDI  ...   28-03-2026   31-04-2026
36        37       ABDIMALIK HAMDI  ...   28-03-2026   31-04-2026
37        38              ASMA ALI  ...   28-03-2026   31-04-2026
38        39             SARWA ALI  ...   28-03-2026   31-04-2026
39        40           SADIK DAHIR  ...   28-03-2026   31-04-2026
40        41       ABDIRAHMAN ADEN  ...   28-03-2026   31-04-2026
41        42      BAHSAN ABDULLAHI  ...   28-03-2026   31-04-2026
42        43             ADAN ABDI  ...   28-03-2026   31-04-2026

[43 rows x 24 columns]

In [19]:
report.to_csv('grade9Processed1.csv', index=False)